export const MICROFRONTEND_NAME = {
  ABOUT: 'About',
  BROWSE: 'Browse',
  RESTAURANT: 'Restaurant',
}

// TODO: think about CORS
export const MICROFRONTEND_HOST = {
  [MICROFRONTEND_NAME.ABOUT]: process.env.REACT_APP_MICROFRONTEND_HOST_ABOUT,
  [MICROFRONTEND_NAME.BROWSE]: process.env.REACT_APP_MICROFRONTEND_HOST_BROWSE,
  [MICROFRONTEND_NAME.RESTAURANT]:
    process.env.REACT_APP_MICROFRONTEND_HOST_RESTAURANT,
}
